baseURL = "https://raynorpat.com/"
locale = "en-US"
title = "Patrick Raynor"
disableKinds = ["taxonomy", "term"]

[params]
  author = "Patrick Raynor"
  description = "Patrick Raynor's personal site and blog"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
